### ISSUE TITLE
运行mian不行

### ISSUE THREAD

**Issue by lmr187044581** [yqchilde/JDMemberCloseAccount#10]
-
![image](https://user-images.githubusercontent.com/46223422/118952509-99195180-b98e-11eb-9ced-a10b1fcef500.png)
这个是什么问题

**Comment by taojr95** [comment]
config.json里面的"userName"是中文吧，把中文删了就行

**Comment by 9527cfc** [comment]
代码软件编辑时使用UTF-8 编码保存

**Comment by lmr187044581** [comment]
解决了，就是那个UTF8编码问题，谢谢各位
