### ISSUE TITLE
Mac 配合iPhone

### ISSUE THREAD

**Issue by Uncledone** [yqchilde/JDMemberCloseAccount#101]
Mac 配合iPhone目前无法获取到验证码，电脑端防火墙开启关闭都没有用，显示的那个访问IP手机端打不开，但在手机访问那个ip的时候偶尔会出现获取验证码123456，求教怎样解决。之前的版本都用的好好的，上次那个有段不能自动发送验证码，看你更新后，跟进了，然后就出现了上述问题。![image](https://user-images.githubusercontent.com/84342165/134673186-530a896f-97fb-4743-becb-799eb781d7c5.jpeg)![image](https://user-images.githubusercontent.com/84342165/134673204-4b630fa1-e93b-48ab-be35-594d688b3b64.png)

**Comment by yqchilde** [comment]
1. 是越狱的ios吗，如果不是，不应该是用ocr识别验证吗，而不是用jd_wstool
2. 手机需要访问控制台打印的完整监听地址，如果不能访问，说明手机与电脑不在同一个网段下，因为192.168是内网

**Comment by Uncledone** [comment]
是未越狱的没用使用jd_wstool，手机和电脑连接的都是同一个无线。要怎样使手机与电脑在同一个网段下，谢谢大佬了





------------------ 原始邮件 ------------------
发件人: Yqchilde ***@***.***&gt;
发送时间: 2021年9月24日 20:26
收件人: yqchilde/JDMemberCloseAccount ***@***.***&gt;
抄送: Uncledone ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[yqchilde/JDMemberCloseAccount] Mac 配合iPhone (#101)





  
是越狱的ios吗，如果不是，不应该是用ocr识别验证吗，而不是用jd_wstool 

手机需要访问控制台打印的完整监听地址，如果不能访问，说明手机与电脑不在同一个网段下，因为192.168是内网

**Comment by yqchilde** [comment]
通过看你的日志，看到你开了内置的jd_wstool（sms_captcha.js_wstool: true），如果是使用ocr是不需要开启的。
我在tg群里回复你了，可以在群里讨论下
