### ISSUE TITLE
批量退会黑号了？

### ISSUE THREAD

**Issue by jkhuangfu** [yqchilde/JDMemberCloseAccount#102]

**Comment by jkhuangfu** [comment]
现在退会手机号直接乱码了不是手机号码了

**Comment by jkhuangfu** [comment]
![image](https://user-images.githubusercontent.com/20948189/135193105-064fffba-6a7f-47fd-ab53-faa63d15aa27.png)

**Comment by yqchilde** [comment]
在群里回你了，是在页面上就直接显示乱码了是吗？

**Comment by yqchilde** [comment]
退会的手机号是和入会相关联的，我新入会几家退了也没有事，可以在tg联系我，我用你的号码测试一下

**Comment by yqchilde** [comment]
这个图不是你的吧，是群里另一个哥们的。

**Comment by jkhuangfu** [comment]
> 这个图不是你的吧，是群里另一个哥们的。

嗯呢  借用的图 我也是这种情况，应该是其他脚本问题，我试了，手动入会不会有问题。closed掉吧

**Comment by yqchilde** [comment]
ok，因为我无法复现，如果你复现了，可以联系我一起看看
