### ISSUE TITLE
退会手机号位置变成一端字母了

### ISSUE THREAD

**Issue by Loliwy** [yqchilde/JDMemberCloseAccount#103]
手机号位置处现在变成AAxxxxxxx之类的了

**Comment by yqchilde** [comment]
店铺是今天用入会脚本加入的吗

**Comment by Loliwy** [comment]
我看了一下好像是的，下拉到最后的看手机号那里是正常的

**Comment by mrwangsg** [comment]
确实乱码啦，并且不能发送短信。
我都以为是黑了，看到有人也有这个问题，我就安心啦。
【顺便提一下，可以了解一下bmob数据库，免费开源的。可以做为验证码的中转站】

![电话号码乱码，以及不能发送验证码](https://user-images.githubusercontent.com/15097460/135590982-9e2da9a1-da91-476b-bc37-8367f506e9ae.png)
