### ISSUE TITLE
入会数量比较多，只想退会一部分店铺，能否加入部分退会店铺？

### ISSUE THREAD

**Issue by zlj6856** [yqchilde/JDMemberCloseAccount#105]

**Comment by mrwangsg** [comment]
看一下配置文件说明，你可以完全匹配，保留店铺

**Comment by mrwangsg** [comment]
> > 看一下配置文件说明，你可以完全匹配，保留店铺
> 
> 请问用青龙面板怎么入会？几天了 提示我不在白名单中

我没有使用过面板入会，我自己修改了一下入会程序。直接使用github的action功能，配合docker镜像使用。【再说，你留言在退会程序这里，不太合适的吧】

**Comment by yqchilde** [comment]
如有其它疑惑，请再次打开该issue，由于时间太久未回复，先关掉了。
