### ISSUE TITLE
退会手机号码读取错误

### ISSUE THREAD

**Issue by seeoneco** [yqchilde/JDMemberCloseAccount#108]
![image](https://user-images.githubusercontent.com/86553484/136757515-affa3ca5-8c62-4e4f-8bc6-bffca77d0b88.png)
![image](https://user-images.githubusercontent.com/86553484/136757747-4744c477-096e-4406-a1ab-a30480255de7.png)

出现这个问题挺长时间的了，猜测问题出现的原因是退会之后再次入会，多次这样就会造成这种情况

**Comment by yqchilde** [comment]
@seeoneco @feishi12121 
已更新，尝试测一下
