### ISSUE TITLE
手机号码乱码退会逻辑修复

### ISSUE THREAD

**Issue by xieshang** [yqchilde/JDMemberCloseAccount#109]
作者好，
近期出现退会手机号乱码，经他人验证页面等待30分钟后刷新即可，现对你的代码进行了调整和实现了该功能：
1、当发现手机乱码时，自动新建一个标签，把所有乱码的页面都新建放在一旁，并记录最后一个乱码页面的出现时间；
2、继续退能成功退的；
3、所有能退的卡都退完后，等待最后一个乱码页面时间到达31分钟；
4、通过切换和刷新标签页实现乱码页面的刷新并执行退会；

**直接下载这个，已更新为最新版本**
[支持手机号乱码退会.zip](https://github.com/yqchilde/JDMemberCloseAccount/files/7356392/main.zip)

**Comment by Iy204** [comment]
确实30分钟后刷新有正确的手机号了，可是你最后发的这个运行不了啊，提示尾号不对，明明和我设置的尾号是对的。

**Comment by xieshang** [comment]
> 确实30分钟后刷新有正确的手机号了，可是你最后发的这个运行不了啊，提示尾号不对，明明和我设置的尾号是对的。

尾号检测没有动过，你可以试试不要在配置文件里限制尾号。

**Comment by Iy204** [comment]
> > 确实30分钟后刷新有正确的手机号了，可是你最后发的这个运行不了啊，提示尾号不对，明明和我设置的尾号是对的。
> 
> 尾号检测没有动过，你可以试试不要在配置文件里限制尾号。

我下载了新版本，好像可以了。
