### ISSUE TITLE
你好 我想问下提示 WebSocket监听时发生了问题，请检查是否开启外部jd_wstool工具或者使用内置的jd_wstool或者5201端口是否开放

### ISSUE THREAD

**Issue by isslower** [yqchilde/JDMemberCloseAccount#117]
WebSocket监听时发生了问题，请检查是否开启外部jd_wstool工具或者使用内置的jd_wstool或者5201端口是否开放
笔记本
win10笔记本 防火墙关闭了的，后面也打开了 把1-63355全部放行了
杀毒软件也退了的。
手机方面 
MacroDroid 权限给了 后台弹出界面  显示悬浮窗 读取短信  通知类短信
IP 设置的是笔记本IP ，一个WIFI下  通信正常。
Config.yaml
配置了JD的KEY 没做其他修改

小米手机 
win10环境
感谢

**Comment by isslower** [comment]
手机能收到验证码，然后报错闪退
![image](https://user-images.githubusercontent.com/45580748/141952433-6f3b334c-8d0c-4471-8797-5ebc4517da4a.png)
参考的操作是你推荐的科技玩家那篇文章
再次表示感谢

**Comment by yqchilde** [comment]
报这个错误原因是外面的jd_wstool可执行工具或者配置中开启了内置的jd_wstool，这两个是二选一的关系，请检查下是否两个都打开了

**Comment by isslower** [comment]
可以了 谢谢
