### ISSUE TITLE
ssl.SSLCertVerificationError

### ISSUE THREAD

**Issue by hi-dajun** [yqchilde/JDMemberCloseAccount#118]
![image](https://user-images.githubusercontent.com/47079069/142353665-2a2fb531-5067-47cb-8b0b-27b5563e5937.jpeg)老哥帮看下这个是什么原因？

**Comment by yqchilde** [comment]
下载模型时，网络问题，开着代理下吧，模型在github，比较慢

**Comment by DengYunJun** [comment]
> 下载模型时，网络问题，开着代理下吧，模型在github，比较慢

好的谢谢，晚上开全局试试
