### ISSUE TITLE
验证码位置点击错误，尝试再试一次

### ISSUE THREAD

**Issue by wangyuan0217** [yqchilde/JDMemberCloseAccount#119]
![image](https://user-images.githubusercontent.com/12730214/142798333-3e92095c-de90-41e0-a27d-789b0603fef7.png)

win64+McrriDroid+python3.9， config中默认的，image_captcha的type是yolov4 ， 不过改成local就可以识别了

**Comment by yqchilde** [comment]
好的，近期我复现一下

**Comment by yqchilde** [comment]
@dd178 好像和numpy或opencv_python版本有关，用requestment.txt里面的版本是没错的，升级了下新版复现了，先待定吧

**Comment by yvanliang** [comment]
cv2装目前最新的4.5.5.62会导致这个问题，按requestments里的4.5.2.54没问题
