### ISSUE TITLE
ios会一直运行

### ISSUE THREAD

**Issue by zz23** [yqchilde/JDMemberCloseAccount#12]
![image](https://user-images.githubusercontent.com/33677983/118991353-3f2c8200-b9b6-11eb-8d43-2e84f728fd86.png)
ios会一直获取短信，不会执行操作

**Comment by yqchilde** [comment]
优化了一下获取策略，如果定位不准，看一下项目目录生成的 ios_code_pic.png 图片位置在哪里
此外，坐标和电脑分辨率有关，如果分辨是是1080P，那么qq截图识别的坐标就是刚好一比一的，比我的是4k显示器，是以百分之200显示的，那所有坐标就要乘以2了。

**Comment by zz23** [comment]
是要截图整个屏幕吗？

**Comment by zz23** [comment]
辛苦大佬了

**Comment by yqchilde** [comment]
截需要识别的区域的左上角和右下角坐标，先把投屏位置固定好，然后手机打开短信界面，通常每个短信验证码收到的位置都是固定的，截图指定的区域来识别

**Comment by zz23** [comment]
好的，谢谢

**Comment by boopzk22** [comment]
我也报tile cannot extend outside image，生成的 ios_code_pic.png 图片都打不开-。-

**Comment by imqimu** [comment]
加1，楼上一样的问题

**Comment by zz23** [comment]
应该是坐标的问题，重新弄下再试试

**Comment by yqchilde** [comment]
尝试着加一下报错行数代码，参考这个
[添加调试报错行数](https://github.com/yqchilde/JDMemberCloseAccount/commit/4ca4d8a15170ee41b390096f3fd656f225b50d3a)

这样我可以定位到哪一行出的错，没在项目更新是怕错误太多刷屏

**Comment by imqimu** [comment]
![image](https://user-images.githubusercontent.com/72058508/119074111-0675c280-ba21-11eb-9921-d8688a59b72a.png)
新鲜的报错来了

**Comment by yqchilde** [comment]
@boopzk22 @zz23 应该是位置的错误，导致截图失败，坐标顺序是 左x 左y 右x 右y
![image](https://user-images.githubusercontent.com/36953759/119074952-8e100100-ba22-11eb-84a9-ee08ead841bc.png)

**Comment by imqimu** [comment]
就是截取这里的坐标，还是无法运行

**Comment by zz23** [comment]
> @ boopzk22 @ zz23应该是位置的错误，导致截图失败，坐标顺序是左x左y右x右y
> ![图像](https://user-images.githubusercontent.com/36953759/119074952-8e100100-ba22-11eb-84a9-ee08ead841bc.png)

我来试试

**Comment by boopzk22** [comment]
@yqchilde 大佬，有这样的验证码
![image](https://user-images.githubusercontent.com/84125068/119083099-ec90ab80-ba31-11eb-8888-4360e0aea9a4.png)
会导致识别错误，能否加个。的判断？或者60秒之后重新再次发送一个验证码，这样直到范围内的验证码就可以取到

**Comment by yqchilde** [comment]
@boopzk22 
因为原来是按照转成6位数字做的，刚才更新了，优化OCR识别，可以扩大区域，使用正则匹配

**Comment by boopzk22** [comment]
> @boopzk22
> 因为原来是按照转成6位数字做的，刚才更新了，优化OCR识别，可以扩大区域，使用正则匹配

大佬牛逼！实测OK了，稳的一笔
