### ISSUE TITLE
jd_wstool问题

### ISSUE THREAD

**Issue by lmr187044581** [yqchilde/JDMemberCloseAccount#13]
我用tasker监听他已经监听到了，而且显示已复制验证码，但是这个jd_wstool他不会显示监听到验证码，就只有一直运行在那里不动，这个是什么原因

**Comment by zz23** [comment]
是什么手机，看看短信有没有验证码保护

**Comment by lmr187044581** [comment]
> 是什么手机，看看短信有没有验证码保护

没有，已经给权限了，就是说手机端我已经能够获取并复制这个验证码了，但是电脑端我收不到，他只有那个监听在那里运行而已

**Comment by yqchilde** [comment]
确保在同个网络下了吗？
用手机浏览器访问 http://你的IP:5201/publish?smsCode=12345，看是否能访问成功
如果不成功，说明网络不在一个局域网下，windows环境可以用 `ipconfig` 查看网络ip，macos用 `ifconfig`

**Comment by lmr187044581** [comment]
> [http://你的IP:5201/publish?smsCode=12345](http://%E4%BD%A0%E7%9A%84IP:5201/publish?smsCode=12345%EF%BC%8C%E7%9C%8B%E6%98%AF%E5%90%A6%E8%83%BD%E8%AE%BF%E9%97%AE%E6%88%90%E5%8A%9F)

可以了，就是那个地址问题，它主要用了ipv6导致不能正确传输

**Comment by lmr187044581** [comment]
> 确保在同个网络下了吗？
> 用手机浏览器访问 [http://你的IP:5201/publish?smsCode=12345，看是否能访问成功](http://%E4%BD%A0%E7%9A%84IP:5201/publish?smsCode=12345%EF%BC%8C%E7%9C%8B%E6%98%AF%E5%90%A6%E8%83%BD%E8%AE%BF%E9%97%AE%E6%88%90%E5%8A%9F)
> 如果不成功，说明网络不在一个局域网下，windows环境可以用 `ipconfig` 查看网络ip，macos用 `ifconfig`

谢谢哈

**Comment by lmr187044581** [comment]
> 确保在同个网络下了吗？
> 用手机浏览器访问 [http://你的IP:5201/publish?smsCode=12345，看是否能访问成功](http://%E4%BD%A0%E7%9A%84IP:5201/publish?smsCode=12345%EF%BC%8C%E7%9C%8B%E6%98%AF%E5%90%A6%E8%83%BD%E8%AE%BF%E9%97%AE%E6%88%90%E5%8A%9F)
> 如果不成功，说明网络不在一个局域网下，windows环境可以用 `ipconfig` 查看网络ip，macos用 `ifconfig`

又有点新问题了，我用图鉴识别，但是他识别不成功，就是不显示注销成功，但是他又跳下一个，显示出了点小问题什么的，手动没有问题

**Comment by yqchilde** [comment]
就是图形验证码识别失败，然后接着跳下一家？

**Comment by lmr187044581** [comment]
> 就是图形验证码识别失败，然后接着跳下一家？
嗯，我去查图鉴记录也没有识别记录

**Comment by yqchilde** [comment]
试试目前的最新版本看看

**Comment by lmr187044581** [comment]
> 试试目前的最新版本看看
我没有卡了，我再看看，现在新问题是我打开了jd westool但是运行main他说没有开

**Comment by yqchilde** [comment]
把报错发上来看看吧

**Comment by lmr187044581** [comment]
> 把报错发上来看看吧


![image](https://user-images.githubusercontent.com/46223422/119215675-bf133300-bb01-11eb-8e6d-1d99362b6645.png)
就显示这样就直接闪退了

**Comment by yqchilde** [comment]
@lmr187044581 查下python哪个版本

**Comment by lmr187044581** [comment]
> @lmr187044581 查下python哪个版本

又解决一个，就是python问题

**Comment by yqchilde** [comment]
已修复 https://github.com/yqchilde/JDMemberCloseAccount/commit/6268a87558ccaf4a8a64bd94426971aeeef1c161
