### ISSUE TITLE
2022.01-图片验证码识别失效

### ISSUE THREAD

**Issue by yqchilde** [yqchilde/JDMemberCloseAccount#134]
目前京东更改了图片点选式验证码，改为了轨迹验证码，暂未有对应解决算法

**Comment by Biercenter** [comment]
原来如此，感谢这么好用的工具，期待之后有解决的方法。

**Comment by xxhhlk** [comment]
轨迹用图鉴能不能识别，我看到是有这个类别的

**Comment by yqchilde** [comment]
> 轨迹用图鉴能不能识别，我看到是有这个类别的

图鉴有，但是鉴于费用还是有点贵，不考虑了

**Comment by htyjswf** [comment]
> > 轨迹用图鉴能不能识别，我看到是有这个类别的
> 
> 图鉴有，但是鉴于费用还是有点贵，不考虑了

****图鉴和超级鹰，只要填账号密码就行了嘛?**
像下面这样，二选一，填一下账号密码？**


# image_captcha 图形验证码相关
# image_captcha.type: 图形验证码类型，可选：local、cjy、tj、yolov4
# image_captcha.cjy_username: 超级鹰账号，仅在 image_captcha.type 为 cjy 时需要设置
# image_captcha.cjy_password: 超级鹰密码，仅在 image_captcha.type 为 cjy 时需要设置
# image_captcha.cjy_soft_id: 超级鹰软件ID，仅在 image_captcha.type 为 cjy 时需要设置
# image_captcha.cjy_kind: 超级鹰验证码类型，仅在 image_captcha.type 为 cjy 时需要设置，且该项目指定为 9101
# image_captcha.tj_username: 图鉴账号，仅在 image_captcha.type 为 tj 时需要设置
# image_captcha.tj_password: 图鉴密码，仅在 image_captcha.type 为 tj 时需要设置
# image_captcha.tj_type_id: 图鉴验证码类型，仅在 image_captcha.type 为 tj 时需要设置，且该项目指定为 19
# yolov4_weights: yolov4权重文件路径，仅在 image_captcha.type 为 yolov4 时需要设置
# yolov4_cfg: yolov4配置文件路径，仅在 image_captcha.type 为 yolov4 时需要设置
# yolov4_net_size: yolov4网络size，仅在 image_captcha.type 为 yolov4 时需要设置
image_captcha:
  type: "yolov4"
  cjy_username: "123"
  cjy_password: "123"
  cjy_soft_id: ""
  cjy_kind: 9101
  tj_username: "456"
  tj_password: "456"
  tj_type_id: 19
  yolov4_weights: "yolov4/yolov4-tiny-custom.weights"
  yolov4_cfg: "yolov4/yolov4-tiny-custom.cfg"
  yolov4_net_size: 512

**Comment by yqchilde** [comment]
> 

目前用不了，没写写针对图鉴识别轨迹的代码，目前代码是原来的逻辑

**Comment by yqchilde** [comment]
> > > 轨迹用图鉴能不能识别，我看到是有这个类别的
> > 
> > 
> > 图鉴有，但是鉴于费用还是有点贵，不考虑了
> 
> ****图鉴和超级鹰，只要填账号密码就行了嘛?** 像下面这样，二选一，填一下账号密码（超级鹰再多一个软件ID），其他不动？**
> 
> image_captcha: type: "yolov4" cjy_username: "123" cjy_password: "123" cjy_soft_id: "123" cjy_kind: 9101 tj_username: "456" tj_password: "456" tj_type_id: 19 yolov4_weights: "yolov4/yolov4-tiny-custom.weights" yolov4_cfg: "yolov4/yolov4-tiny-custom.cfg" yolov4_net_size: 512

目前用不了，没写写针对图鉴识别轨迹的代码，目前代码是原来的逻辑

**Comment by edwinzjh** [comment]
小改了程序 可以实现 但是一个是有点慢 正确率也一般般 还有就是太贵了 没什么意思

**Comment by m1w22** [comment]
2022年5月31日20点变成滑块验证。。。

**Comment by yqchilde** [comment]
> 2022年5月31日20点变成滑块验证。。。

滑块后面依旧存在手动选择指定的图案验证码
<img width="500" alt="image" src="https://user-images.githubusercontent.com/36953759/171522430-3f1ada51-6f6f-49c3-905b-d6074df745b5.png">

**Comment by yqchilde** [comment]
2022-06-06 代码已更新，由于去掉了轨迹验证码，换成了滑块验证码活点选式，现已可以利用图鉴等打码平台完成识别，后续再说本地识别
