### ISSUE TITLE
超级鹰打码上报报错

### ISSUE THREAD

**Issue by wspzf** [yqchilde/JDMemberCloseAccount#14]
开始调用超级鹰识别验证码
超级鹰验证失败，上报错误
发生了一点小问题： ("invalid literal for int() with base 10: ''",)
![image](https://user-images.githubusercontent.com/43857401/119067617-18516880-ba15-11eb-8ed9-c57ad3e042c1.png)

**Comment by yqchilde** [comment]
好的，我查看一下

**Comment by zz23** [comment]
用图鉴吧

**Comment by yqchilde** [comment]
修了下，看看，这次应该会把报错信息输出出来

**Comment by wspzf** [comment]
> 修了下，看看，这次应该会把报错信息输出出来

可以正常打码了，
上个版本开始出现了不自动发送验证码的问题，昨天的老版本可以正常自动发送验证码

**Comment by yqchilde** [comment]
发送验证码是啥意思？把验证码填充到selenium的浏览器窗口验证码输入框？当前这个版本有吗

**Comment by wspzf** [comment]
> 发送验证码是啥意思？把验证码填充到selenium的浏览器窗口验证码输入框？当前这个版本有吗

![image](https://user-images.githubusercontent.com/43857401/119071354-3ec6d200-ba1c-11eb-8ee3-d3abcac254bb.png)
这个，要手动点击才会发送短信验证码

**Comment by zz23** [comment]
是的，我也是这样的问题

**Comment by zz23** [comment]
![123](https://user-images.githubusercontent.com/33677983/119072241-be08d580-ba1d-11eb-9d84-68324f91f033.jpg)
大佬把代码注释掉了，改下就好了

**Comment by yqchilde** [comment]
尴尬，调试完忘记开启了，抱歉，手动先把注释打开把，我马上更新

**Comment by yqchilde** [comment]
好了

**Comment by zz23** [comment]
> 好了

大佬有电报群嘛

**Comment by yqchilde** [comment]
没有，就在藏经阁活跃一下

**Comment by zz23** [comment]
> 没有，就在藏经阁活跃一下

好吧，我进不了藏经阁

**Comment by wspzf** [comment]
可以了，谢谢大佬
