### ISSUE TITLE
M1 mac用easy ocr截图文件为0字节

### ISSUE THREAD

**Issue by tjcfnerd** [yqchilde/JDMemberCloseAccount#144]
python版本为3.10.4，PyCharm 2022.1 (Community Edition)，因为pillow 8.2不适用于python 3.10，自己手动装的9.1.0，easyocr装的1.4.2，试了1.4.1也是相同情况，其他都是自动拉取的
<a href="https://imgtu.com/i/LGyFyQ"><img src="https://s1.ax1x.com/2022/04/15/LGyFyQ.png" alt="LGyFyQ.png" border="0" /></a>
<a href="https://imgtu.com/i/LGXuQg"><img src="https://s1.ax1x.com/2022/04/15/LGXuQg.png" alt="LGXuQg.png" border="0" /></a>

**Comment by yqchilde** [comment]
我查阅了一下，目前该库还没有支持M1
https://github.com/JaidedAI/EasyOCR/issues/406
