### ISSUE TITLE
获取本地卡包的时候报错{'code': '2', 'echo': 'the current API does not exist'}

### ISSUE THREAD

**Issue by zlhdd108** [yqchilde/JDMemberCloseAccount#146]
获取本地卡包的时候报错
```powershell
[2022-04-27 13:45:13] [ERROR] xxxx >> {'code': '2', 'echo': 'the current API does not exist'}
[2022-04-27 13:45:13] [ERROR] xxxx >> {'code': '2', 'echo': 'the current API does not exist'}
```
![image](https://user-images.githubusercontent.com/16465666/165451482-08c5d5a9-e0e6-436b-a101-d47d23ad7334.png)

**Comment by weizuo0408** [comment]
附议

**Comment by feishi12121** [comment]
同错，希望得到解决！！！

**Comment by zlhdd108** [comment]
看起来应该是jd的api换了……自己抓了一下，没抓到对应的，而且好像都加了签名验证了……

**Comment by yqchilde** [comment]
@zlhdd108  @feishi12121  @feishi12121 
已修复，重新down代码或者git pull

https://github.com/yqchilde/JDMemberCloseAccount/commit/b516a9d2950424596e591bf0c3b5dc999722c7cd
