### ISSUE TITLE
不会自动点发送验证码

### ISSUE THREAD

**Issue by douzicao** [yqchilde/JDMemberCloseAccount#15]
不自动点击，手动点击后后面的都可以自动跑，难道是我分辨率问题？电脑时老电脑，720P的屏幕。

**Comment by zz23** [comment]
![123](https://user-images.githubusercontent.com/33677983/119072751-9fefa500-ba1e-11eb-9fc7-22a2fe2b4492.jpg)
把这块注释掉的代码，改下就行

**Comment by yqchilde** [comment]
抱歉，调试完忘记把注释打开了，已更新，或手动把注释打开一下

**Comment by douzicao** [comment]
> 抱歉，调试完忘记把注释打开了，已更新，或手动把注释打开一下

多谢

**Comment by douzicao** [comment]
> ![123](https://user-images.githubusercontent.com/33677983/119072751-9fefa500-ba1e-11eb-9fc7-22a2fe2b4492.jpg)
> 把这块注释掉的代码，改下就行

多谢
