### ISSUE TITLE
ios识别验证码

### ISSUE THREAD

**Issue by 546220777** [yqchilde/JDMemberCloseAccount#16]
大佬 请问下投屏识别验证码时间怎么改啊  这识别太快的 新验证码还没发过来呢  就开始识别的  然后就识别到上一条的验证码

**Comment by WYEEE** [comment]
我是验证IOS通知横幅的位置，但是百度OCR 5秒才重试一次，要是能调整OCR刷新时间就好了，不知道有没有除了百度之外的文字识别API。

**Comment by 546220777** [comment]
> 我是验证IOS通知横幅的位置，但是百度OCR 5秒才重试一次，要是能调整OCR刷新时间就好了，不知道有没有除了百度之外的文字识别API。

我现在是手动删短信  其实在发送验证码后3到5S后再开始识别验证码的话就可以了

**Comment by WYEEE** [comment]
> > 我是验证IOS通知横幅的位置，但是百度OCR 5秒才重试一次，要是能调整OCR刷新时间就好了，不知道有没有除了百度之外的文字识别API。
> 
> 我现在是手动删短信 其实在发送验证码后3到5S后再开始识别验证码的话就可以了

找到解决方法了。

作者刷新OCR的时间默认5s，苹果横幅停留时间也是5s，加上收取短信不及时的时间，容易错过读取。

解决方法：到captcha文件夹修改baidu_ocr.py文件，把里面的所有5改成1。

结果：这样1s监控1次横幅验证码区域，成功率100%。我已经把200多个连续退完了，中间没有断。

**Comment by yqchilde** [comment]
已在config.json中添加延迟时间配置，默认为5秒，可自行设置

**Comment by 546220777** [comment]
> > > 我是验证IOS通知横幅的位置，但是百度OCR 5秒才重试一次，要是能调整OCR刷新时间就好了，不知道有没有除了百度之外的文字识别API。
> > 
> > 
> > 我现在是手动删短信 其实在发送验证码后3到5S后再开始识别验证码的话就可以了
> 
> 找到解决方法了。
> 
> 作者刷新OCR的时间默认5s，苹果横幅停留时间也是5s，加上收取短信不及时的时间，容易错过读取。
> 
> 解决方法：到captcha文件夹修改baidu_ocr.py文件，把里面的所有5改成1。
> 
> 结果：这样1s监控1次横幅验证码区域，成功率100%。我已经把200多个连续退完了，中间没有断。
我

> > > 我是验证IOS通知横幅的位置，但是百度OCR 5秒才重试一次，要是能调整OCR刷新时间就好了，不知道有没有除了百度之外的文字识别API。
> > 
> > 
> > 我现在是手动删短信 其实在发送验证码后3到5S后再开始识别验证码的话就可以了
> 
> 找到解决方法了。
> 
> 作者刷新OCR的时间默认5s，苹果横幅停留时间也是5s，加上收取短信不及时的时间，容易错过读取。
> 
> 解决方法：到captcha文件夹修改baidu_ocr.py文件，把里面的所有5改成1。
> 
> 结果：这样1s监控1次横幅验证码区域，成功率100%。我已经把200多个连续退完了，中间没有断。

我把卡插安卓里了  还是安卓退起来舒服

**Comment by zz23** [comment]
![image](https://user-images.githubusercontent.com/33677983/119095742-3afb7580-ba45-11eb-8591-b906a2feea55.png)
  我这识别到不填入

**Comment by yqchilde** [comment]
因为原来是按照转成6位数字做的，刚才更新了，优化OCR识别，可以扩大区域，使用正则匹配

**Comment by zz23** [comment]
> 因为原来是按照转成6位数字做的，刚才更新了，优化OCR识别，可以扩大区域，使用正则匹配

好的 辛苦大佬

**Comment by zz23** [comment]
> 因为原来是按照转成6位数字做的，刚才更新了，优化OCR识别，可以扩大区域，使用正则匹配

![image](https://user-images.githubusercontent.com/33677983/119103169-6eda9900-ba4d-11eb-8c5c-0698737377ad.png)
大佬图形无法验证

**Comment by yqchilde** [comment]
@zz23 
在config.json 设置 selenium超时时间长一点 selenium_timeout
默认是30秒，你可以设置60或其他

**Comment by zz23** [comment]
> @zz23
> 在config.json 设置 selenium超时时间长一点 selenium_timeout
> 默认是30秒，你可以设置60或其他

还是一样的显示

**Comment by yqchilde** [comment]
有其他报错吗，如果报停留图形验证码界面超时，代表没有手点也没有使用图形验证，你用的什么打码平台

**Comment by zz23** [comment]
> 有其他报错吗，如果报停留图形验证码界面超时，代表没有手点也没有使用图形验证，你用的什么打码平台![image](https://user-images.githubusercontent.com/33677983/119104737-2de38400-ba4f-11eb-97c7-60f683d5ef4f.png)
百度ocr

**Comment by yqchilde** [comment]
是不是点过一次验证码，位置点错了，导致卡住

**Comment by zz23** [comment]
> 是不是点过一次验证码，位置点错了，导致卡住

没点过诶，我尝试了很多次，然后频繁验证码，东哥都给我打电话了

**Comment by yqchilde** [comment]
@zz23 图形验证码用了什么平台，超级鹰还是图鉴？百度OCR只是识别短信的，不要误解

**Comment by zz23** [comment]
> @ zz23图形验证码用了什么平台，超级鹰还是图鉴？百度OCR只是识别短信的，不要误解

我懂了，我没开图鉴

**Comment by lmr187044581** [comment]
> @zz23 图形验证码用了什么平台，超级鹰还是图鉴？百度OCR只是识别短信的，不要误解

现在问题很多啊，就是同一个局域网http://192.168.1.100:5201/publish?smsCode=12345用这种测试显示请先开启python端
