### ISSUE TITLE
执行出错

### ISSUE THREAD

**Issue by 9527cfc** [yqchilde/JDMemberCloseAccount#2]
哥，执行的时候出错，是不是要用调试模式模拟手机还是啥。

**Comment by 9527cfc** [comment]
我两个cookie都添加了

**Comment by yqchilde** [comment]
不用改调试模式啊，在哪一步报错的

**Comment by 9527cfc** [comment]
就是这个获取列表的函数，如果code等于0的时候，往数组里填数据的时候报错

**Comment by yqchilde** [comment]
在109行后，print(ret)，看看是啥数据，我又测试了个号，没复现

**Comment by 9527cfc** [comment]
显示用户未登录😂

**Comment by 9527cfc** [comment]
获取电脑cookie那步是不是要短信登录，我是扫码登录的

**Comment by 9527cfc** [comment]
浏览器变小的上一部我看注释里写的验证是否登录成功啊

**Comment by yqchilde** [comment]
一个是电脑端cookie，需要 `python3 add_cookie.py` 然后扫码验证，提示登录成功会自动关闭
另一个是手机端ck，就复制常用的pt_key那个就行

**Comment by yqchilde** [comment]
手机端ck可能有问题？重新生成一个

**Comment by 9527cfc** [comment]
换了还是这样，{'code': '0', 'businessCode': '3', 'message': '用户未登录'}

**Comment by yqchilde** [comment]
ok，我再用别的号测测吧

**Comment by 9527cfc** [comment]
好了好了

**Comment by 9527cfc** [comment]
只填了key没填那个pin，最开始都填了也不管用，现在填上好了。

**Comment by 9527cfc** [comment]
就剩下转发验证码了😂

**Comment by 9527cfc** [comment]
谢谢哥，辛苦了

**Comment by yqchilde** [comment]
ok，好了就行，此外websocket服务端自己搭建好了吗？没有的话，我已经将代码和编译好的包提交到仓库了，可以看使用说明
1. 可以手动运行websocket 服务端
2. 可以直接运行release中对应电脑系统的websocket服务端工具，解压后可直接运行，是可执行文件

**Comment by 9527cfc** [comment]
正在研究中

**Comment by 9527cfc** [comment]
解压出来不能执行啊，名称为jdwstool

**Comment by 9527cfc** [comment]
我装个go语言试试直接执行

**Comment by yqchilde** [comment]
稍等，我重新编译下

**Comment by yqchilde** [comment]
更新了

**Comment by 9527cfc** [comment]
哥，能把task配置打包传下吗，这个软件不会用

**Comment by yqchilde** [comment]
看看这个视频后半部分，我也是刚学，照着写的

https://www.bilibili.com/video/BV1J7411L7Bn

**Comment by 9527cfc** [comment]
好的谢谢

**Comment by 9527cfc** [comment]
taske是发送到网络，wifi共享吗

**Comment by yqchilde** [comment]
监听到短信后，发起一个http请求

**Comment by yqchilde** [comment]
![Screenshot_2021-05-18-23-54-18-784_net dinglisch](https://user-images.githubusercontent.com/36953759/118684000-6bb89080-b834-11eb-9e8f-21e8da521fa5.jpg)

**Comment by yqchilde** [comment]
![Screenshot_2021-05-18-23-55-17-801_net dinglisch](https://user-images.githubusercontent.com/36953759/118684121-87bc3200-b834-11eb-91ee-0fca6fe6d2f8.jpg)

**Comment by 9527cfc** [comment]
![Uploading 66024CA9-A8E0-4EEF-9A6A-400AC607A04C.jpeg…]()

**Comment by 9527cfc** [comment]
![Uploading 4F1436BB-2894-4C9F-8F20-EAB03428909C.jpeg…]()

**Comment by 9527cfc** [comment]
我这上传的照片不显示😭

**Comment by yqchilde** [comment]
😺，先睡了，明天我看看其他的自动化软件，ifttt之类的，tasker的导入配置有点不好用

**Comment by 9527cfc** [comment]
我可以了，日志显示有了，我试试

**Comment by 9527cfc** [comment]
发生了一点小问题： (22, '远程计算机拒绝网络连接。', None, 1225, None)  最后一步卡在这里了

**Comment by yqchilde** [comment]
tasker发送的http请求地址记得改成自己的，windows在控制台用 `ipconfig` 查看自己的局域网，或者在运行 `jd_wstool.exe` 时，提示的那个网址也是你的局域网

**Comment by 9527cfc** [comment]
我好像打错符号了，在外面，登我回去看看的

**Comment by 9527cfc** [comment]
没打错，就是远程计算机拒绝连接

**Comment by 9527cfc** [comment]
是不是电脑需要打开某个端口

**Comment by yqchilde** [comment]
是在py端报出来错误，还是哪里的，你说下操作，jd_wstool运行了吗，如果运行了后会启动5201端口，手机用tasker发送的请求是 你的ip加5201端口

**Comment by 9527cfc** [comment]
就是我jdtool跑起来了，然后手机端也设置好了，在跑main的时候，命令行里报错，显示远程计算机拒绝网络连接，我把共享啥的都打开了，没啥用

**Comment by yqchilde** [comment]
config.json 里面这个设置对了吗
"ws_conn_url": "ws://localhost:5201/subscribe",

**Comment by 9527cfc** [comment]
好了好了😭不过tasker有点问题，我再研究研究

**Comment by yqchilde** [comment]
tasker和Macrodroid的配置我都传仓库了，使用这两个软件记得权限给够，读取短信的权限

**Comment by 9527cfc** [comment]
好了，这次彻底好了，tasker我把yzm1 的一给去了。。。所以不管用了

**Comment by 9527cfc** [comment]
嗯嗯，那个超级鹰是不是得花钱啊

**Comment by yqchilde** [comment]
是的，readme我写了价格

**Comment by 9527cfc** [comment]
嗯嗯好的，太感谢了，第一次在git上交流这么久

**Comment by yqchilde** [comment]
ok，我关闭该issue了，有问题再提
