### ISSUE TITLE
用第一家验证缓冲是否刷新问题

### ISSUE THREAD

**Issue by douzicao** [yqchilde/JDMemberCloseAccount#20]
比如我的前12个都是之前的手机号，这几个卡没办法注销了，就会一直提示未刷新，等30s。是不是可以用最后一个名字来验证。

**Comment by hyzaw** [comment]
config中可以配置手机尾号判定

**Comment by douzicao** [comment]
> config中可以配置手机尾号判定

已经配置了，他是用会员名字判断的。这样尾号不一致的一直在前面几个，所以会识别成一直没有刷新列表。

**Comment by hyzaw** [comment]
> > config中可以配置手机尾号判定
> 
> 已经配置了，他是用会员名字判断的。这样尾号不一致的一直在前面几个，所以会识别成一直没有刷新列表。

已提交pr解决这个bug

**Comment by yqchilde** [comment]
合进来了
