### ISSUE TITLE
用图鉴就没成功过是怎么回事？

### ISSUE THREAD

**Issue by KuHai-A** [yqchilde/JDMemberCloseAccount#24]
刚才运行尝试，拿的昨天的版本，ocr识别太快了，但是图鉴还是能准确的。
然后拉取了最新代码，ocr识别优化的很不错了，但是图鉴一次也没成功过，这是什么情况？
输出框那里[xxx，yyy]是图鉴识别到的坐标点？
如果是坐标的话，那[0，0]点取的哪里？是屏幕左上角，还是浏览器左上角，还是那个图片的左上角？
感觉那个坐标明显是很错误的，不知道大家有没有碰到这个情况

**Comment by KuHai-A** [comment]
![code_pic](https://user-images.githubusercontent.com/37091493/119170193-7d4ca300-ba95-11eb-98f1-e54489d0374a.png)
看下截出来保存下来的这个code_pic，左上角定位错了，导致截取的错了，

**Comment by yqchilde** [comment]
上传图鉴的图片是以截下来的code_pic.png 为主，图片左上角为原点，这个再看看其他人没有有类似的问题吧，不好复现

**Comment by KuHai-A** [comment]
看我这个code_pic.png里的截图，从来就没完整过。。。。。。我现在都手动点了，居然没有其它朋友遇到过，也是怪了
![code_pic](https://user-images.githubusercontent.com/37091493/119365212-49b28880-bce2-11eb-9659-5874433e86ed.png)

**Comment by zz23** [comment]
从来也没有这个问题

**Comment by yqchilde** [comment]
@KuHai-A 请问你的电脑屏幕尺寸是多大的，分辨率是多少的

**Comment by KuHai-A** [comment]
@yqchilde 笔记本电脑，忘了多大了，大概15寸左右，分辨率1920*1080。
有可能是因为我用的谷歌内核的浏览器而非谷歌浏览器，晚上回去了我换乘谷歌浏览器再试一次后再给你反馈

**Comment by yqchilde** [comment]
👌
