### ISSUE TITLE
非局域网监控验证码的一种思路

### ISSUE THREAD

**Issue by douzicao** [yqchilde/JDMemberCloseAccount#26]
先用tasker把验证码转发到tg的机器人里面，然后用监控红包雨的那种脚本监控机器人的信息，有验证码的消息就匹配。
![Screenshot_2021-05-22-09-44-09-884_net dinglisch android taskerm](https://user-images.githubusercontent.com/18158418/119211006-4f418000-bae2-11eb-8e7b-3c2c7ab672a8.jpg)

**Comment by yqchilde** [comment]
这种不考虑了，事实上这种处理更麻烦，局域网你可以部署到服务器，代理一下5201端口，就可以公网用了
