### ISSUE TITLE
发生了一点小问题

### ISSUE THREAD

**Issue by underlaw** [yqchilde/JDMemberCloseAccount#28]
发生了一点小问题： ("invalid literal for int() with base 10: ''",)

这是什么意思了 谢谢

**Comment by hyzaw** [comment]
重新拉取仓库 已经修复了

**Comment by underlaw** [comment]
重新拉了，但现在图形不能自动识别，得手动点

**Comment by underlaw** [comment]
请问"baidu_range": [63,217,469,571], 这个参数是验证码图形整个区域还是指那个右下角小图区域

**Comment by underlaw** [comment]
> 重新拉取仓库 已经修复了

大佬在吗

**Comment by yqchilde** [comment]
整个一条短信的区域，来新的短信不是也会顶到最前面吗，那个区域是固定的，

下午会搞一下搞到整个投屏区域

**Comment by underlaw** [comment]
> 整个一条短信的区域，来新的短信不是也会顶到最前面

短信能自动填写了，是弹出的图片识别不能自动

**Comment by underlaw** [comment]
"baidu_app_id": "一串数子",
    "baidu_api_key": "一串代码",
    "baidu_secret_key": "一串代码",
用的百度

**Comment by hyzaw** [comment]
> 整个一条短信的区域，来新的短信不是也会顶到最前面吗，那个区域是固定的，
> 
> 下午会搞一下搞到整个投屏区域

你后来简化的时候 把 == "true"删了 布朗型和文本型可以这样判定吗

**Comment by yqchilde** [comment]
@hyzaw  没有文本型啊，cjy_validation 和 tj_validation，都是布尔型

"cjy_validation": false,
"tj_validation": false,

**Comment by underlaw** [comment]
![image](https://user-images.githubusercontent.com/33020405/119213839-c97b0000-baf4-11eb-920c-b61c5448c614.png)

![image](https://user-images.githubusercontent.com/33020405/119213852-da2b7600-baf4-11eb-9edf-b1830b260d50.png)

**Comment by yqchilde** [comment]
@underlaw 百度那个只是帮助识别短信并填充的，图形验证码想要自动是要用超级鹰或者图鉴打码的，你如果没有手动，又一直等着自动，是不可能点得

**Comment by underlaw** [comment]
> 是帮助识别短信并填充的，图形验证码想要自动是要用超级鹰或者图鉴打码的，

这哦啊，我理解错了，以为百度这个是识别图片验证了

**Comment by underlaw** [comment]
> > 整个一条短信的区域，来新的短信不是也会顶到最前面
> 
> 短信能自动填写了，是弹出的图片识别不能自动

本次运行获取到 50 家店铺会员信息
开始注销店铺 梅林
开始调用图鉴识别验证码
发生了一点小问题： ('string indices must be integers',)
开始注销店铺 洽洽
开始调用图鉴识别验证码
发生了一点小问题： ('string indices must be integers',)
开始注销店铺 联想品牌会员

超级鹰问题
