### ISSUE TITLE
退会链接已失效

### ISSUE THREAD

**Issue by boopzk22** [yqchilde/JDMemberCloseAccount#34]
怎么破
![image](https://user-images.githubusercontent.com/84125068/119288554-58b22000-bc7b-11eb-9ac9-1609d5941cce.png)

**Comment by yqchilde** [comment]
执行完下面最后一行应该有提示让你更新电脑端cookie吧

**Comment by boopzk22** [comment]
> 执行完下面最后一行应该有提示让你更新电脑端cookie吧

哦原来是过期了~报错之后我直接ctrl c了

**Comment by yqchilde** [comment]
电脑端ck过期很快
