### ISSUE TITLE
jd_wstool.exe里的ip不是正确的

### ISSUE THREAD

**Issue by lplbb** [yqchilde/JDMemberCloseAccount#35]
显示的是Vmnet1的ip,不应该是显示以太网的ip吗

**Comment by lplbb** [comment]
这是ipconfig的显示
以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::a113:b120:2566:f817%10
   IPv4 地址 . . . . . . . . . . . . : 10.208.41.70
   子网掩码  . . . . . . . . . . . . : 255.255.248.0
   默认网关. . . . . . . . . . . . . : 10.208.47.254

以太网适配器 VMware Network Adapter VMnet1:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::e9d6:8e04:4a48:d6d%5
   IPv4 地址 . . . . . . . . . . . . : 192.168.131.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . :
---------------------------------------------------------------------
这是jd-wstool.exe的显示
listening on http://192.168.131.1:5201

**Comment by lplbb** [comment]
结果就是，我在tasker配置的也是192.168.131.1:5201后，不会自动输入验证码，目前是一加手机，读取短信的权限都给了

**Comment by yqchilde** [comment]
listening on的地址仅供参考，从本地192.168随机取了一条
直接用ipconfig的能连上就行

**Comment by lplbb** [comment]
那我试试10.208.41.70这个

**Comment by lplbb** [comment]
不知道tasker里的ip填哪个了。。。

**Comment by yqchilde** [comment]
试一下新的release包里编译好的js_wstool，刚重新改了点获取ip方式

**Comment by lplbb** [comment]
好滴！

**Comment by justcopy** [comment]
能不能修改成指定ip监听？我电脑旧版和新版都会识别错误的ip地址。

**Comment by justcopy** [comment]
![image](https://user-images.githubusercontent.com/45755204/119502645-bab67680-bd9c-11eb-97b1-5b3fe60353ff.png)

![image](https://user-images.githubusercontent.com/45755204/119502686-c3a74800-bd9c-11eb-993e-f652f5df1981.png)

![image](https://user-images.githubusercontent.com/45755204/119502736-d3269100-bd9c-11eb-8b5b-e6c1f7040323.png)

**Comment by yqchilde** [comment]
@justcopy 要指定只能自己部署然后映射个公网IP，内网的话，软件只是获取了可参考的IPV4地址，如果不能用，可以自行查看下内网IP，保证手机电脑可以在同个网络下即可

**Comment by 546220777** [comment]
同样问题  jd_wstool.exe里面显示169.254开头的  但是我局域网应该是192.168

**Comment by yqchilde** [comment]
@546220777 这个呀，不影响，只要是本地的IP就行，软件列举出来的仅做参考，本地不止一个IP，我更新了，把所有的IP都列举出来了，可以挨个尝试

https://github.com/yqchilde/JDMemberCloseAccount/releases/tag/1.0.2

**Comment by 546220777** [comment]
> @546220777 这个呀，不影响，只要是本地的IP就行，软件列举出来的仅做参考，本地不止一个IP，我更新了，把所有的IP都列举出来了，可以挨个尝试
> 
> https://github.com/yqchilde/JDMemberCloseAccount/releases/tag/1.0.2

恩  可以了
