### ISSUE TITLE
只跑第一轮退会的店铺，成功后，再跑还是之前跑过的店铺，提示连接失效

### ISSUE THREAD

**Issue by yftu** [yqchilde/JDMemberCloseAccount#36]
电脑端 COOKIE,和PHONE [COOKIE都更新多次，还是无法解决。怕缓存没更新，试了两天了还是这样
![JDMEMBERCLOSE](https://user-images.githubusercontent.com/62737154/119611500-58598680-be2d-11eb-9ea9-a0f59cc0e203.JPG)

**Comment by yftu** [comment]
[http://yftu999.vicp.cc:8084/api/raw/users/yftu/JDMEMBERCLOSE.JPG?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJsb2NhbGUiOiJ6aC1jbiIsInZpZXdNb2RlIjoibW9zYWljIiwic2hvd0hpZGRlbiI6ZmFsc2UsInBlcm0iOnsiYWRtaW4iOnRydWUsImV4ZWN1dGUiOnRydWUsImNyZWF0ZSI6dHJ1ZSwicmVuYW1lIjp0cnVlLCJtb2RpZnkiOnRydWUsImRlbGV0ZSI6dHJ1ZSwic2hhcmUiOnRydWUsImRvd25sb2FkIjp0cnVlfSwiY29tbWFuZHMiOltdLCJsb2NrUGFzc3dvcmQiOmZhbHNlLCJvdHAiOmZhbHNlLCJvdHBLZXkiOiJGRTJVNERHNjdFVllNTFlPS1MzWktPNU9XWExYUVJaRSJ9LCJleHAiOjE2MjIwOTUxNTUsImlhdCI6MTYyMjAwODc1NSwiaXNzIjoiRmlsZSBCcm93c2VyICB2Mi45LjMvNGUzMWFkYTZcbkJ1aWx0IEZvciAgIDogbGludXgvYW1kNjRcbkdvIFZlcnNpb24gIDogZ28xLjE0LjJcblJlbGVhc2UgRGF0ZTogMjAyMDA0MzAtMTA0NiJ9.EG8xNKLMDSe1ab7rnBffW_sp0r_Uin4Ay5ClzI6kJlc&inline=true](url)

**Comment by yftu** [comment]
![Uploading JDMEMBERCLOSE.JPG…]()

**Comment by yohanceli** [comment]
+10086

**Comment by zz23** [comment]
自己查看下这些会员卡是否是加入的 ，没有加入的会员卡是这样显示的

**Comment by yftu** [comment]
> 自己查看下这些会员卡是否是加入的 ，没有加入的会员卡是这样显示的
查了都没加入，问题是拉不到加入的？且每次都拉这几个店铺

**Comment by yohanceli** [comment]
跑完一轮后过个5分钟10分钟再跑就可以了，京东那边有缓存，我已经跑完了所有店铺了

**Comment by yftu** [comment]
> 跑完一轮后过个5分钟10分钟再跑就可以了，京东那边有缓存，我已经跑完了所有店铺了

还是不行，看来是哪里出问题了

**Comment by yqchilde** [comment]
@yftu 手机查看下卡包里面的店铺名字，和脚本里面读取出来的一致吗

**Comment by yftu** [comment]
> @yftu 手机查看下卡包里面的店铺名字，和脚本里面读取出来的一致吗

不一致，比如脚本里“巴黎欧莱雅”，卡包里店铺是“欧莱雅京东自营官方旗舰店”是否是这个问题导致的？

**Comment by yqchilde** [comment]
@yftu 和这个没关系，先手动退了卡包中的第一家然后再跑脚本试试，你这个情况还真没遇到过，通常情况下就是cookie不完整才会出现，也可以试试把电脑和手机的ck在配置文件中清空后再填写

**Comment by yftu** [comment]
> @yftu 和这个没关系，先手动退了卡包中的第一家然后再跑脚本试试，你这个情况还真没遇到过，通常情况下就是cookie不完整才会出现，也可以试试把电脑和手机的ck在配置文件中清空后再填写

有个店铺 “宝菲凡”没有会员退出界面，是不是这个店铺造成的？其他的店铺都退出了的

**Comment by yftu** [comment]
昨天手动退了好几个会员后，今天正常可以用了，估计是某几个店铺的问题
