### ISSUE TITLE
请问这个是怎么回事？

### ISSUE THREAD

**Issue by ruitianchen** [yqchilde/JDMemberCloseAccount#39]
![image](https://user-images.githubusercontent.com/57313069/119844845-5aaa0680-bf3b-11eb-8a25-70866d026126.png)

![image](https://user-images.githubusercontent.com/57313069/119845042-862cf100-bf3b-11eb-9b75-171b542e2d1c.png)
![image](https://user-images.githubusercontent.com/57313069/119845191-a3fa5600-bf3b-11eb-946c-a749c399d318.png)

**Comment by yqchilde** [comment]
你是用的投屏然后百度OCR识别验证码？

**Comment by ruitianchen** [comment]
不是的，我是安卓手机；手机的验证码传不到windows电脑上，手机网络连接的是电脑热点，tasker的ip写的是电脑的本地ip（192.168....)+5201，手机浏览器能访问的通电脑ip(192.168...)+5201，然后tasker只能把验证码复制到剪切板上，发不到电脑上。tasker该给的权限也都给了，请老哥指点一下

**Comment by yqchilde** [comment]
config.json 里面 device 写了什么内容，如果是android要留空

**Comment by yqchilde** [comment]
config.json 里面 device 写了什么内容，如果是android要留空

**Comment by 546220777** [comment]
这是jd_wstool.exe  ip不正确

**Comment by ruitianchen** [comment]
已成功解决，谢谢作者和各位！
