### ISSUE TITLE
验证码要怎么从手机端传到电脑端？已下载了TASKER

### ISSUE THREAD

**Issue by lanyucomputer** [yqchilde/JDMemberCloseAccount#43]
百度ID和超级鹰ID已正确填到配置文了，手动可以正常退会了，想自动但没有反应，更改了在extra/tasker/监听京东退会验证码.prf.xml里面的IP，也运行了WS_TOOL,但电脑端没有反应，收不到验证码

**Comment by yqchilde** [comment]
tasker和百度OCR是两个东西，二选一就行，安卓直接用tasker即可
收不到验证码要检查tasker的权限有没有读取短信权限和剪切板的权限
