### ISSUE TITLE
图鉴识别  偶尔会有报错：开始调用图鉴识别验证码 发生了一点小问题： ('string indices must be integers',)

### ISSUE THREAD

**Issue by KodoShinichi** [yqchilde/JDMemberCloseAccount#44]
图鉴识别  偶尔会有报错
![image](https://user-images.githubusercontent.com/26167263/120065083-1be29080-c0a2-11eb-9e7b-de56d00b5bd0.png)

**Comment by yqchilde** [comment]
参考下面这个，在代码中加点调试，然后发一下报错，我分析下

https://github.com/yqchilde/JDMemberCloseAccount/commit/4ca4d8a15170ee41b390096f3fd656f225b50d3a

**Comment by KodoShinichi** [comment]
![image](https://user-images.githubusercontent.com/26167263/120099552-a264a400-c16e-11eb-9ee9-ec689c9e0a49.png)



开始注销店铺 西贡咖啡
开始调用图鉴识别验证码
发生了一点小问题： ('string indices must be integers',)
Traceback (most recent call last):
  File "e:\下载集\GitHub项目\京东退会项目\JDMemberCloseAccount\main.py", line 313, in main
    if not auto_identify_captcha_click():
  File "e:\下载集\GitHub项目\京东退会项目\JDMemberCloseAccount\main.py", line 273, in auto_identify_captcha_click
    pic_str = resp["result"]
TypeError: string indices must be integers

**Comment by KodoShinichi** [comment]
出现的频率好像并不高

**Comment by yqchilde** [comment]
新版把图鉴的错误输出优化过了，如果还有问题可以进来tg群说一下
