### ISSUE TITLE
短信传送不到电脑上

### ISSUE THREAD

**Issue by lanny520** [yqchilde/JDMemberCloseAccount#46]
安卓的两个app都试过，按照大佬的图片设置的，读取短信的粘贴板权限也给了，ip也是通的。短信就是传不到电脑上

**Comment by yqchilde** [comment]
想用手机浏览器访问，看jd_wstool是否能获取到数据
例如：
http://你的IP:5201/publish?smsCode=12345

**Comment by lanny520** [comment]
![72f7ddfff50f291a](https://user-images.githubusercontent.com/77821876/120579064-72ace900-c459-11eb-8554-10874077287a.png)
能收到，但是为空

**Comment by yqchilde** [comment]
不是，你用手机浏览器访问了吗？看起来这还是用tasker或Macrodroid发的

**Comment by lanny520** [comment]
![7cd84557ce917de1](https://user-images.githubusercontent.com/77821876/120592588-b19a6900-c470-11eb-8fca-94ab427d4b76.png)
浏览器可以发送过去，app里是按你的图设置的呀，这是什么问题？

**Comment by buse88** [comment]
权限全部都给了，会不会是搜索数字0-9这个变量哪里错了，用的都是英文的符号应该也对啊

**Comment by yqchilde** [comment]
浏览器可以，Macrodroid不可以的话，那看下Macrodroid的日志吧
![Screenshot_2021-06-03-14-37-43-952_com arlosoft m](https://user-images.githubusercontent.com/36953759/120598839-528d2200-c479-11eb-8702-bb48b506924d.jpg)

**Comment by lanny520** [comment]
![Uploading Screenshot_2021-06-03-14-40-47-039_com.arlosoft.macrodroid.jpg…]()
日志

**Comment by lanny520** [comment]
![Screenshot_2021-06-03-14-28-50-756_com arlosoft macrodroid](https://user-images.githubusercontent.com/77821876/120599446-1c9c6d80-c47a-11eb-9979-139b096622ab.jpg)
配置

**Comment by yqchilde** [comment]
我看那个日志像在读剪切板的时候没允许然后报错了😹，那你在发个应用权限的图吧

**Comment by lanny520** [comment]
![IMG_20210603_145352](https://user-images.githubusercontent.com/77821876/120600639-9719bd00-c47b-11eb-8090-97a83295b291.jpg)
权限给了呀，还有别的权限要给吗？

**Comment by yqchilde** [comment]
我已经不知道为啥报错了，试试最后这个法子，不行我真不知道怎么弄了，下载我用的这个版本的MacroDroid

[https://wwa.lanzoui.com/iSwocpqow3a](https://wwa.lanzoui.com/iSwocpqow3a)

**Comment by lanny520** [comment]
谢谢大佬，搞定了
