### ISSUE TITLE
新版本ocr识别不到短信投屏了~

### ISSUE THREAD

**Issue by boopzk22** [yqchilde/JDMemberCloseAccount#48]
图片是对的
![image](https://user-images.githubusercontent.com/84125068/120582378-f3baaf00-c45e-11eb-9b55-88be3fcc61b5.png)

**Comment by yqchilde** [comment]
我去看看

**Comment by yqchilde** [comment]
报错是不是 {'error_code': 18, 'error_msg': 'Open api qps request limit reached'} ?

我也是报这个错，是百度那边的问题，重新创建应用，领一下免费额度就好了

![image](https://user-images.githubusercontent.com/36953759/120589467-79445c00-c46b-11eb-848e-30b10682bce5.png)

**Comment by h605290713** [comment]
> 报错是不是 {'error_code': 18, 'error_msg': 'Open api qps request limit reached'} ?
> 
> 我也是报这个错，是百度那边的问题，重新创建应用，领一下免费额度就好了
> 
> ![image](https://user-images.githubusercontent.com/36953759/120589467-79445c00-c46b-11eb-848e-30b10682bce5.png)

领取了还是这个报错

**Comment by yqchilde** [comment]
解决了吗？
