### ISSUE TITLE
大佬 能获取到短信并且有通知，但是电脑端显示不出来验证码是为何呢，win10 64位系统+小米手机

### ISSUE THREAD

**Issue by buse88** [yqchilde/JDMemberCloseAccount#49]
![QQ截图20210603111945](https://user-images.githubusercontent.com/79825350/120582467-14830480-c45f-11eb-9194-afcb32860e14.png)

**Comment by buse88** [comment]
还有个问题，就是哪个jd_wstool.exe经常会卡死 导致手机tasker提示运行出错，但是没任何提示，光标还会一闪一闪

**Comment by yqchilde** [comment]
先用手机浏览器访问，看jd_wstool是否能获取到数据
例如：
http://你的IP:5201/publish?smsCode=12345

**Comment by buse88** [comment]
提示先启动python端脚本，实际上那边已经再运行了

**Comment by buse88** [comment]
![Uploading 0.png…]()

**Comment by buse88** [comment]
![Uploading 0.png…]()

**Comment by buse88** [comment]
![IMG_20210603_132719](https://user-images.githubusercontent.com/79825350/120592038-c6401800-c402-11eb-8d0d-66598686a71a.jpg)
就这个提示，电脑端都在运行了，

**Comment by buse88** [comment]
![0](https://user-images.githubusercontent.com/79825350/120595350-d4dcfe00-c407-11eb-86dd-d0da54f8c748.png)
网址输入提示这个，但是验证码还是获取不到

**Comment by yqchilde** [comment]
看下tasker的日志吧，看起来是没有读取到短信验证码，小米手机要给tasker权限，读取通知类短信权限和剪切板权限

**Comment by buse88** [comment]
权限全部都给了，会不会是搜索数字0-9这个变量哪里错了，用的都是英文的符号应该也对啊

**Comment by yqchilde** [comment]
要不是试试Macrodroid吧，这个简单

**Comment by lanny520** [comment]
> 要不是试试Macrodroid吧，这个简单

Macrodroid我试过，一点反应也没有
![Screenshot_2021-06-03-14-28-50-756_com arlosoft macrodroid](https://user-images.githubusercontent.com/77821876/120597819-1ad1aa80-c478-11eb-91fd-0d484ff87985.jpg)
也是根据你图设置的，没一点反应

**Comment by yqchilde** [comment]
针对websocket的测试，加了点测试代码，更新下新的代码，测试方法为
https://github.com/yqchilde/JDMemberCloseAccount#%E6%B5%8B%E8%AF%95

**Comment by buse88** [comment]
![Screenshot_2021-06-03-14-41-47-064_net dinglisch android taskerm](https://user-images.githubusercontent.com/79825350/120599349-00aeb280-c40d-11eb-99c5-0adb1b400b10.jpg)
这个是运行日志，大神帮我看下

**Comment by yqchilde** [comment]
@buse88 直接换Macrodroid，然后导入项目中的配置试试吧，tasker有点迷

**Comment by buse88** [comment]
macrodroid导入配置是导入这个文件的是吗  监听京东退会验证码.macro

**Comment by yqchilde** [comment]
@buse88  嗯

**Comment by buse88** [comment]
导入了，测试都是没问题的，但是退会脚本运行起来就监听不到了

**Comment by yqchilde** [comment]
看下日志，正常的是这样

![Screenshot_2021-06-03-14-37-43-952_com arlosoft m](https://user-images.githubusercontent.com/36953759/120598839-528d2200-c479-11eb-8702-bb48b506924d.jpg)

**Comment by buse88** [comment]
我把tasker的配置导入就可以运行了，之前自己配置的估计没配置好导致的

**Comment by buse88** [comment]
大神，那个本地验证码输入有教程吗

**Comment by yqchilde** [comment]
本地验证码输入是啥意思，现在就是利用tasker监听到再用jd_wstool工具监听到直接填入启动的浏览器窗口直接输入验证码

**Comment by buse88** [comment]
就是那个今天新增加的本地识别验证码，是怎么配置让运行的时候调用这个py文件自动点击验证码

**Comment by yqchilde** [comment]
README中有写
当cjy_validation 和 tj_validation 都为false时，启动本地引擎识别

**Comment by buse88** [comment]
看到了，本地打码很给力！现在人均双卡手机，如果能增加两个账号运行就好了，然后再增加一次运行限制多少个店铺(预防黑号)，那就爽歪歪了，哈哈

**Comment by yqchilde** [comment]
同时运行两个短信会乱的，后面那个限制每次运行多少店铺这个好弄，晚点就更

**Comment by buse88** [comment]
一个config配置两个ck然后按顺序运行，一个退完了再退另外一个，这样也会乱吗

**Comment by yqchilde** [comment]
这个后续再说吧

**Comment by buse88** [comment]
好辛苦大神了
