### ISSUE TITLE
运行过一遍退不完全，再运行就显示cookie失效，咋办？

### ISSUE THREAD

**Issue by joshua76y** [yqchilde/JDMemberCloseAccount#54]
D:\python\JDMemberCloseAccount>python main.py
本次运行获取到 1 家店铺会员信息
开始注销店铺 宝洁
当前店铺退会链接已失效，即将跳过，当前店铺链接为：
https://shopmember.m.jd.com/member/memberCloseAccount?venderId=100000000000438
本轮全部店铺都失效，有可能是电脑端cookie失效导致，请重新添加

**Comment by yqchilde** [comment]
等4-5分钟，有缓存

**Comment by joshua76y** [comment]
> 等4-5分钟，有缓存

第二次运行其实是一段时间之后的，我今晚再重试吧，感谢

**Comment by AntonVanke** [comment]
> > 等4-5分钟，有缓存
> 
> 
> 
> 第二次运行其实是一段时间之后的，我今晚再重试吧，感谢

你可以检查一下config中的电脑cookie和手机cookie是否是同一个账号

**Comment by joshua76y** [comment]
> > > 等4-5分钟，有缓存
> > 
> > 
> > 第二次运行其实是一段时间之后的，我今晚再重试吧，感谢
> 
> 你可以检查一下config中的电脑cookie和手机cookie是否是同一个账号

还是同样的问题，已经超过12小时了。cookie之前跑的一遍是用同一套的，也尝试重新获取，还是不行

**Comment by yqchilde** [comment]
@joshua76y 拉新版吧，现在统一用手机ck管理了
方便的话可以在tg群沟通，https://t.me/jdMemberCloseAccount

**Comment by yftu** [comment]
我之前遇到一样的问题，后来手动退了一些店铺后，就可以拉到新的退会店铺了，但是现在还有一个问题就是明明有很多店铺是加会员的，但是每次拉到的要退会的店铺都只是6-7个，退会完成后就结束了，其中还有不知道怎么电话号码不对的店铺，这个问题一直不知道怎么解决
