### ISSUE TITLE
老哥好  软件配置能更详细一些吗  

### ISSUE THREAD

**Issue by Junya520** [yqchilde/JDMemberCloseAccount#6]
我测试是可以连接到websocket  但是无法获取到短信内容发送不出来

**Comment by 9527cfc** [comment]
是不是你tasker有问题

**Comment by Junya520** [comment]
这两个软件我都试过  测试是可以发送到websocket   就是验证码提取不出来

**Comment by 9527cfc** [comment]
jdtool提示什么，你tasker网络请求的上一部加个tast提示，看看你发送的数据是什么

**Comment by yqchilde** [comment]
提取不出来，可能是手机有保护短信设置，可以查查怎么关闭，还有就是读取短信权限要给

**Comment by Junya520** [comment]
我是安卓11小米手机  可能提取不到....

**Comment by yqchilde** [comment]
小米手机应该没啥问题，我是红米k30s，需要在权限中把通知短信权限给了，小米的验证码是一个单独的权限，叫通知类短信

**Comment by 9527cfc** [comment]
我也是k30s

**Comment by Junya520** [comment]
我已经搞定了 没问题
