### ISSUE TITLE
越狱ios验证码会重复发

### ISSUE THREAD

**Issue by zhanggaolei001** [yqchilde/JDMemberCloseAccount#68]
重复发送相同验证码,导致后面填写的验证码是错误的,希望ios这边判断下拿到的最新验证码是不是旧的,如果是就先不post给服务器

**Comment by c939984606** [comment]
同样的问题，只发送第一个店铺的验证码，后面的都发第一个

**Comment by yqchilde** [comment]
来tg讨论一下吧，关于ios那边不是很清楚
