### ISSUE TITLE
jd_wstool不显示ip

### ISSUE THREAD

**Issue by zz23** [yqchilde/JDMemberCloseAccount#7]
大佬我这个怎么不显示IP地址啊，Windows也是一样不显示IP地址
<img width="585" alt="QQ20210520-140945@2x" src="https://user-images.githubusercontent.com/33677983/118928002-35365f00-b975-11eb-987a-cc1cf85635f1.png">

**Comment by yqchilde** [comment]
可能在ipv6下，mac设备直接终端输入 `ifconfig` 看看局域网ip吧

**Comment by zz23** [comment]
好的 谢谢
