### ISSUE TITLE
jd_wstool几次都被windows安全中心删除，而使用内置websocket监听又存在"module 'signal' has no attribute 'SIGALRM'"的错误

### ISSUE THREAD

**Issue by EchoChan314** [yqchilde/JDMemberCloseAccount#75]
希望作者大大有空修复下Windows平台下内置websocket监听的bug吧。

**Comment by yqchilde** [comment]
请问内置的websocket有什么bug吗，贴一下截图或debug日志

**Comment by EchoChan314** [comment]
> 请问内置的websocket有什么bug吗，贴一下截图或debug日志

![image](https://user-images.githubusercontent.com/5077551/124341200-52ee1980-dbed-11eb-94bf-faf5090e862c.png)
![image](https://user-images.githubusercontent.com/5077551/124341206-613c3580-dbed-11eb-9bab-2bb422309bc9.png)

**Comment by yqchilde** [comment]
暂未有好的解决方案，先挂着再想想方案

**Comment by yqchilde** [comment]
现在有解决方案了，请测试一下吧
https://github.com/yqchilde/JDMemberCloseAccount/pull/89

**Comment by EchoChan314** [comment]
@yqchilde 可以了，谢谢大佬们的解决。
