### ISSUE TITLE
大佬，我有个想法，你看看能不能实现！

### ISSUE THREAD

**Issue by mzljjkj** [yqchilde/JDMemberCloseAccount#76]
iOS软件有一个叫青椒云的，云电脑，如果在云电脑上跑退会项目，短信验证码直接可以不用监听，云电脑用的手机输入法，收到短信验证码直接复制剪贴板了，退会软件直接读取剪贴板即可

**Comment by yqchilde** [comment]
貌似在ios上没有三方可以读取剪切板
