### ISSUE TITLE
为啥我运行完python3 add_cookie.py没反应，是我下的版本有问题还是啥

### ISSUE THREAD

**Issue by taojr95** [yqchilde/JDMemberCloseAccount#8]
![Dingtalk_20210520143726](https://user-images.githubusercontent.com/37699177/118931138-35385e00-b979-11eb-831e-1a6900d2f5fa.jpg)
![Dingtalk_20210520143802](https://user-images.githubusercontent.com/37699177/118931143-36698b00-b979-11eb-84cb-58fc8aaedd2b.jpg)
![Dingtalk_20210520144006](https://user-images.githubusercontent.com/37699177/118931217-4d0fe200-b979-11eb-8625-80b20302714b.jpg)

**Comment by yqchilde** [comment]
没有浏览器窗口打开吗? 把无头模式关闭，config.json里headless设置为false

**Comment by 9527cfc** [comment]
你那个安装命令都报错了

**Comment by taojr95** [comment]
![Dingtalk_20210520150339](https://user-images.githubusercontent.com/37699177/118934163-a299be00-b97c-11eb-9c1a-81ccb154683d.jpg)
都是默认值也不行，"binary": "C:\Program Files\Google\Chrome\Application\chrome.exe"这样也没反应

**Comment by taojr95** [comment]
> 你那个安装命令都报错了

那只是让我用最新版的吧 不是error

**Comment by 9527cfc** [comment]
你得pipe不是最新版本，百度一个最新版本的升级命令，就好了

**Comment by taojr95** [comment]
那我试下

**Comment by taojr95** [comment]
![Dingtalk_20210520151807](https://user-images.githubusercontent.com/37699177/118936337-0ae99f00-b97f-11eb-829f-f90ddee04040.jpg)
更新完还是这样。。。

**Comment by 9527cfc** [comment]
不是更新那个，是更新pip3  另外你试试python main. py

**Comment by taojr95** [comment]
python main.py这样可以 python3 main.py不行

**Comment by 9527cfc** [comment]
因为你第一次安装py，所以路径默认py，用py就行

**Comment by taojr95** [comment]
![Dingtalk_20210520154822](https://user-images.githubusercontent.com/37699177/118940089-f3acb080-b982-11eb-9f53-74d2bc0a7a88.jpg)
![Dingtalk_20210520154834](https://user-images.githubusercontent.com/37699177/118940235-15a63300-b983-11eb-8d00-486cd1dcf916.jpg)
![Screenshot_20210520_154843_com arlosoft macrodroid](https://user-images.githubusercontent.com/37699177/118940251-1a6ae700-b983-11eb-9f38-844149e3b8bb.jpg)

到这一步web就一直收不到验证码 是我哪里配置不对吗

**Comment by 9527cfc** [comment]
我没用这个我用的tasker。你确定使用get请求吗

**Comment by zz23** [comment]
我也是收不到短信

**Comment by taojr95** [comment]
是get请求我抓包看到了，可能还是http://:5021这里没显示IP的问题？
![image](https://user-images.githubusercontent.com/37699177/118941738-9e719e80-b984-11eb-9de4-be1c9825190f.png)

**Comment by 9527cfc** [comment]
我的意思是手机端发送不应该是respond 请求吗？他脚本监控的好像不是get请求

**Comment by 9527cfc** [comment]
jdtool放到同一目录了吗

**Comment by zz23** [comment]
放了，还显示这个

**Comment by taojr95** [comment]
终于监听到验证码了，我是华为手机，有个短信验证码保护功能默认开启的，去短信设置里关闭就能监听到啦~
![image](https://user-images.githubusercontent.com/37699177/118955782-99671c00-b991-11eb-8999-4f4cc1ada4fe.png)

**Comment by zz23** [comment]
我说我华为手机怎么不行，换了小米就行了。但是图片验证没有执行
