### ISSUE TITLE
安卓可以使用开源软件短信转发器

### ISSUE THREAD

**Issue by 3184876** [yqchilde/JDMemberCloseAccount#80]
[](https://github.com/pppscn/SmsForwarder)
我觉得这个也可以是一个思路，最起码可以绕过局域网，一般我手机验证码都是用这个软件进行转发到钉钉或者微信

**Comment by yqchilde** [comment]
可以的，其实目的就是通过HTTP请求去传递验证码，手机端无论用啥能传过去就行，利用任一一个可以监听到短信并能发送HTTP请求的都可以。
