### ISSUE TITLE
为啥安卓手机，Tasker | Macrodroid 监听不到短信，需要root吗

### ISSUE THREAD

**Issue by lsq543658134** [yqchilde/JDMemberCloseAccount#81]
为啥安卓手机，Tasker | Macrodroid 监听不到短信，需要root吗？Macrodroid 也没用报错日志

**Comment by yqchilde** [comment]
这两个都不需要root，请检查权限是否给了
https://github.com/yqchilde/JDMemberCloseAccount#常见问题
