### ISSUE TITLE
运行main.py报错AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by d8899p** [yqchilde/JDMemberCloseAccount#84]
运行main.py时，cmd命令窗口报错：  
File "C:\Users\10069\Desktop\JDMemberCloseAccount-1.0.3 (2)\JDMemberCloseAccount-1.0.3\main.py", line 220, in main
    self.browser.get("https://m.jd.com/")
AttributeError: 'NoneType' object has no attribute 'get'

请问如何解决？

**Comment by yqchilde** [comment]
浏览器配置错误了，怎么配的

**Comment by d8899p** [comment]
重新安装了下浏览器，问题解决~
