### ISSUE TITLE
麻烦修改下说明，折腾好久没成功最后发现竟然是这个问题

### ISSUE THREAD

**Issue by SQDFeng** [yqchilde/JDMemberCloseAccount#88]
#  手机端cookie，是pt_key=xxx;pt_pin=xxx; 
cookie :  " " 
debug :  false 

实际上是pt_pin=xxx;pt_key=xxx;
本来是把别的项目的key直接拿来用，结果万万没想到识别不出来是顺序问题（震惊）
![5U3V GU9UJ3OJLZI Y_`LIT](https://user-images.githubusercontent.com/11267586/126362696-b909f389-e058-45d7-b5ca-3ef8f1f8ac2a.jpg)

**Comment by yqchilde** [comment]
不影响的，我都是用青龙里的ck，顺序就是pt_key在前，并不影响

**Comment by yqchilde** [comment]
![image](https://user-images.githubusercontent.com/36953759/126414239-0886f389-5791-421f-83d5-e333f5356588.png)
