### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by bluewatercg** [yqchilde/JDMemberCloseAccount#9]
IOS 实现了自动退会，大佬代码怎么给到你

**Comment by 9527cfc** [comment]
给我发份呗，315324793@qq.com

**Comment by bluewatercg** [comment]
已经发给大佬整理了，等大佬更新

**Comment by zz23** [comment]
好的

**Comment by yqchilde** [comment]
发上来了，记得看readme，我晚点上来看消息，先尝试看看会不会用

**Comment by h605290713** [comment]
> 发上来了，记得看readme，我晚点上来看消息，先尝试看看会不会用

所有都设置好了 不读取我给的定位 一直在刷新页面

**Comment by yqchilde** [comment]
优化了一下获取策略，如果定位不准，看一下项目目录生成的 ios_code_pic.png 图片位置在哪里
此外，坐标和电脑分辨率有关，如果分辨是是1080P，那么qq截图识别的坐标就是刚好一比一的，比我的是4k显示器，是以百分之200显示的，那所有坐标就要乘以2了。
