### ISSUE TITLE
一加9PRO COLOROS系统无法读取短信

### ISSUE THREAD

**Issue by yftu** [yqchilde/JDMemberCloseAccount#92]
MACRODROID 无法读取短信，权限都给了，但是就是无法触发，不知道有没有人也遇到这个问题？

**Comment by yqchilde** [comment]
具体的请贴一下macrodroid执行日志，有tg账号的推荐来群里截图交流一下

**Comment by yftu** [comment]
短信隐私保护关了就OK了，以前用7TPRO 刷的氧，没有这个问题，所以换了新机一开始不行就来提问了

**Comment by 2375399351** [comment]
大佬短信隐私保护关了，这个在哪里关闭？是隐私替身吗?
