### ISSUE TITLE
华为手机，给了短信权限，关了验证码安全保护，还是不行

### ISSUE THREAD

**Issue by TZbeyond** [yqchilde/JDMemberCloseAccount#97]
WebSocket监听时发生了问题 (22, '远程计算机拒绝网络连接。', None, 1225, None)
应该时权限问题但是不知道是哪个权限，大佬能不能给指点一下
进电报群的时候没注意底下机器人的验证，被踢了，现在进不去了

**Comment by yqchilde** [comment]
没打开jd_wstool吧
电报名叫什么，给你解一下

**Comment by TZbeyond** [comment]
stone
感谢
我现在打开无障碍试一下，不再报错变成了超时，jd_wstool一直开着呢
![image](https://user-images.githubusercontent.com/61233559/132080960-963de472-789c-4aa2-a0c8-fbb13e1296e6.png)

**Comment by yqchilde** [comment]
已解封
jd_wstool开启要和手机连在一起，手机用macrodroid，里面填写的是jd_wstool监听的ip才行，否则无法转发短信，从而导致超时
